### PR TITLE
Fixed undo redo, help command now works offline, and allow sorting by remind date

### LINKED ISSUE #258: [PE-D] Help Function
Help Window redirects to a webpage instead of displaying the available help tab. Might not work without internet.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: terencemah/ped#6

### LINKED ISSUE #266: [PE-D] Undo/redo Command does not work restore undone coupon
Steps to reproduce: 
1) clear
2) add n/A s/20% e/05-05-2020
3) add n/B s/20% e/05-05-2020
4) add n/C s/20% e/05-05-2020
5) undo
6) undo
7) redo
8) redo
9) undo
10) undo
11) redo
12) add n/D s/20% e/05-05-2020
13) undo
14) redo

At step 14, the image is as shown. Note that Coupon C is restored instead of Coupon D as in line 12. 

The log file is as attached. 

[couponstash.txt](https://raw.githubusercontent.com/nigelnnk/ped/master/files/af997f29-1421-40f1-9731-3ce06abe0697.txt)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: nigelnnk/ped#5

### PR DESCRIPTION
**Pull request by nelsontky**
Fixed undo redo bug. Fixes #266 

Help command now works offline. The command will extract a `help.html` file from the jar file if it is not present in current directory. Thus, this feature does not work when running from intellij, this only works when running from jar file. Fixes #258 

Sort command works with the `r/` prefix now.

### CODE REVIEW

File: src/main/java/csdev/couponstash/logic/commands/HelpCommand.java [hunk 1]
```diff
@@ -28,29 +33,62 @@
...
+        return new CommandResult(SHOWING_HELP_MESSAGE);
+    }
+
+    /**
+     * Get URI of help.html. If help.html is not extracted from jar file yet,
+     * extract it.
+     * @return URI of help.html
+     * @throws CommandException
+     */
+    private static URI getHelpHtmlPath() throws CommandException {
```
Comment (ChesterSim) [inline src/main/java/csdev/couponstash/logic/commands/HelpCommand.java:50]: What a tough solution to code. Good work!

**Review by ChesterSim — APPROVED** [review]
Overall LGTM!
