### PR TITLE
Chester fix archive bugs

### LINKED ISSUE #221: Make use of hasExpired()
- For archiving expired coupons etc.

### LINKED ISSUE #277: Duplicate archived to unarchived coupon

### LINKED ISSUE #290: Add boolean value to Archived

### PR DESCRIPTION
**Pull request by ChesterSim**
Resolve #290
Resolve #277

### CODE REVIEW

File: src/main/java/csdev/couponstash/logic/parser/CliSyntax.java [hunk 1]
```diff
@@ -6,7 +6,7 @@
 public class CliSyntax {
 
     /* Prefix definitions */
-    public static final Prefix PREFIX_ARCHIVE = new Prefix("a/"); //For ListCommand
+    public static final Prefix PREFIX_ARCHIVE = new Prefix("a/"); // or ListCommand
```
Comment (alcen) [inline src/main/java/csdev/couponstash/logic/parser/CliSyntax.java:9]: I think it was a mistake to delete the "F"?

File: src/main/java/csdev/couponstash/model/coupon/Archived.java [hunk 2]
```diff
@@ -14,25 +13,24 @@
 
     public static final String VALIDATION_REGEX = "^(true|false)$";
 
-    public final String value;
+    public final Boolean state;
```
Comment (alcen) [inline src/main/java/csdev/couponstash/model/coupon/Archived.java]: Why is object Boolean class used? It could be normal boolean right

**Review by alcen — CHANGES_REQUESTED** [review]
Thanks for the effort put in! But I have some questions about the implementation

**Review by alcen — APPROVED** [review]
OK looks good!!
